### ISSUE TITLE
OTA-ish type control for TVDb

### ISSUE THREAD

**Issue by maxGreenblatt** [plexinc-agents/TheTVDB.bundle#15]
The ability to use TMDb (episode thumbnail) images (with TVDb images as a fallback) would be great for a lot of people.

**Comment by sullman** [comment]
@kmacinnis This may be an interesting issue to take a look at. There's definite value, while not super time-sensitive. @maxGreenblatt did something similar for movies and we can probably borrow extensively from that for this. He's happy to provide some some direction and answer any questions.
