### ISSUE TITLE
Use DVD order when indicated

### ISSUE THREAD

**Issue by alexchandel** [plexinc-agents/TheTVDB.bundle#19]
TheTVDB lists DVD orders as well as aired orders, and the two are significantly different for some shows. Workarounds to enable the use of DVD order are [convoluted and frail](https://www.reddit.com/r/PleX/comments/36kycs/listing_futurama_in_its_intended_viewing_dvd_order/).

A branch adding the ability to mark shows for which DVD order should be used already exists in [TGVarik/feature/dvd-order](/TGVarik/TheTVDB.bundle/tree/feature/dvd-order).

**Comment by elan** [comment]
We have an internal issue for this, and have made progress on it lately 😬
